export default {
  products: [
    {
      _id: "111111111111111111111111",
      name: 'Trouble "Blush Rush" Bold Pink Hoodie',
      category: "Outerwear",
      image: "/images/product-1.jpg",
      description:
        'Stay cozy and unapologetically bold with the "Blush Out" hoodie from Trouble. This eye-catching pink hoodie is for those who aren’t afraid to stand out and make a statement. Crafted from premium, ultra-soft cotton blend fabric, it’s designed for comfort while turning heads wherever you go.',
      price: 55,
      brand: "Trouble",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "222222222222222222222222",
      name: 'Vexx "Echo" Black & White Sneakers',
      category: "Shoes",
      image: "/images/product-2.jpg",
      description:
        'Step into a new level of style with the Vexx "Echo" sneakers. Featuring a sleek black and white design, these shoes are elevated by a striking red accent that brings energy to every step. Engineered for comfort and designed for impact, the "Echo" sneakers will take your look from simple to standout in no time.',
      price: 60,
      brand: "Vexx",
      rating: 5,
      numReviews: 51,
      countInStock: 16,
    },
    {
      _id: "333333333333333333333333",
      name: 'Concrete "City Hustle" Oversized Denim Jacket',
      category: "Outerwear",
      image: "/images/product-3.jpg",
      description:
        'The Concrete "City Hustle" oversized denim jacket brings a modern twist to a classic look. With a relaxed, oversized fit and carefully crafted distressing, this jacket delivers effortless style while providing the comfort you need for everyday wear. Whether layered over a tee or worn on its own, it’s the perfect piece to complete your laid-back look.',
      price: 75,
      brand: "Concrete",
      rating: 4,
      numReviews: 45,
      countInStock: 0,
    },
    {
      _id: "444444444444444444444444",
      name: 'Ironwood "Vanguard" Brown Blazer',
      category: "Outerwear",
      image: "/images/product-4.jpg",
      description:
        'The Ironwood "Vanguard" brown blazer is the perfect balance of classic tailoring and modern sophistication. Made from a rich, textured fabric, this blazer offers a sharp silhouette that’s versatile enough for both business meetings and evening outings. With its clean lines and refined fit, it’s a timeless addition to any wardrobe.',
      price: 85,
      brand: "Ironwood",
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: "555555555555555555555555",
      name: 'Luxe Allure "Dottie" Polka Dot Shirt Dress',
      category: "Shirts",
      image: "/images/product-5.jpg",
      description:
        'The Luxe Allure "Dottie" shirt dress combines playful polka dots with an elegant, relaxed fit. Crafted from soft, breathable fabric, this black and white dress features a button-down front, flattering waist tie, and classic shirt collar for a polished yet casual look. Perfect for a day out or a laid-back evening, it’s the perfect balance of comfort and style.',
      price: 30,
      brand: "Luxe Allure",
      rating: 3.5,
      numReviews: 89,
      countInStock: 0,
    },
    {
      _id: "666666666666666666666666",
      name: 'Emberlane "Rebel Chic" Brown Blazer & Skirt Set',
      category: "Sets",
      image: "/images/product-6.jpg",
      description:
        'Step into a bold new style with the Emberlane "Rebel Chic" brown blazer and skirt combo. The cropped, cut-off blazer adds a modern twist to the classic tailored look, while the matching skirt offers a sleek, fitted silhouette that complements the outfit perfectly. Crafted from high-quality fabric, this set brings edgy sophistication to your wardrobe, ideal for both professional settings or after-hours outings.',
      price: 85,
      brand: "Emberlane",
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
    {
      _id: "777777777777777777777777",
      name: 'Elysian "Nature’s Grace" Floral Dress',
      category: "Dresses",
      image: "/images/product-7.jpg",
      description:
        'Step into the beauty of nature with the Elysian "Nature’s Grace" floral dress. Featuring a serene blue backdrop adorned with delicate leaves and vibrant flowers, this dress captures the essence of a peaceful natural landscape. Crafted from soft, breathable fabric, it offers effortless comfort and a graceful, timeless style perfect for any occasion.',
      price: 35,
      brand: "Elysian",
      rating: 4,
      numReviews: 23,
      countInStock: 6,
    },
    {
      _id: "888888888888888888888888",
      name: 'Verano "Noir Luxe" Leather Handbag',
      category: "Handbags",
      image: "/images/product-8.jpg",
      description:
        'The Verano "Noir Luxe" leather handbag combines sophistication with durability. Made from high-quality black leather, this bag offers a sleek, structured design that’s perfect for both day-to-day use and evening elegance. With its spacious interior and subtle gold hardware accents, it’s the ultimate accessory for elevating any outfit with effortless style.',
      price: 80,
      brand: "Verano",
      rating: 4.5,
      numReviews: 17,
      countInStock: 4,
    },
    {
      _id: "999999999999999999999999",
      name: 'Ciel "City Breeze" White Button-Up Blouse',
      category: "Shirts",
      image: "/images/product-9.jpg",
      description:
        'The Ciel "City Breeze" white button-up blouse is your go-to for laid-back yet stylish vibes. Made from soft, breathable fabric, this blouse features a relaxed fit with rolled-up sleeves for a casual, easygoing look. Perfect for layering or wearing on its own, it’s a versatile piece that brings a cool, effortless edge to your everyday style.',
      price: 35,
      brand: "Ciel",
      rating: 4,
      numReviews: 25,
      countInStock: 0,
    },
    {
      _id: "121212121212121212121212",
      name: 'Run "Shadow" Black Hoodie',
      category: "Outerwear",
      image: "/images/product-10.jpg",
      description:
        'The Run "Shadow" black hoodie is made for those who move fast and stay ahead. Crafted from a soft, durable fabric, this hoodie features a sleek design with a relaxed fit, making it perfect for everything from morning runs to casual outings. With its minimalist style and signature Run logo, it’s the ideal combination of comfort and performance for your everyday hustle.',
      price: 40,
      brand: "Run",
      rating: 3.5,
      numReviews: 20,
      countInStock: 10,
    },
  ],
};
